language: php

services:
  - mysql
  - docker

addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
      key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - yarn
    - google-chrome-stable

cache:
  yarn: true
  directories:
  - $HOME/.composer/cache/files

php:
- 7.3

env:
- WP_VERSION=latest WP_MULTISITE=0 PLUGIN=gravity-forms-pdf-extended

before_script:
#- chmod -R 777 .
- nvm install 10.15
- ./bin/setup-local-env.sh

script:
- yarn run test:e2e:headless:chrome