language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 5.3
    env: WP_VERSION=4.2 WP_MULTISITE=0
  - php: 5.3
    env: WP_VERSION=4.1 WP_MULTISITE=0
  - php: 5.3
    env: WP_VERSION=4.0 WP_MULTISITE=0
  - php: 5.3
    env: WP_VERSION=3.9 WP_MULTISITE=0

before_script:
  - composer install --prefer-source --optimize-autoloader
  - bash tests/bin/install.sh gravitypdf_test root '' localhost $WP_VERSION

script:
 - phpunit -c phpunit.xml.dist
 - phpunit -c phpunit.xml.dist --group ajax

after_script:
  - php vendor/bin/coveralls --verbose --exclude-no-stmt
