language: generic

services:
  - docker

#branches:
#  only:
#    - master
#    - development
#    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - docker-ce
      - yarn

cache:
  yarn: true
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache

env:
  global:
    - WP_DEVELOP_DIR: ./wordpress
    - INSTALL_COMPOSER: false
    - INSTALL_WORDPRESS: true

before_install:
  - nvm install --lts
  - yarn global add gulp-cli
  - yarn
  - |
    if [[ "$INSTALL_WORDPRESS" = "true" ]]; then
      # Upgrade docker-compose.
      sudo rm /usr/local/bin/docker-compose
      curl -sL https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > docker-compose
      chmod +x docker-compose
      sudo mv docker-compose /usr/local/bin
    fi

install:
  # Build Gravity PDF
  - gulp && yarn build
  - |
    if [[ "$INSTALL_WORDPRESS" = "true" ]]; then
      bash ./bin/install.sh
    fi

jobs:
  fast_finish: true
  include:
    - name: PHP 7.3 unit tests
      env: INSTALL_COMPOSER=true LOCAL_PHP=7.3-fpm
      script:
        - yarn test:php && yarn test:php --group ajax && yarn test:php:multisite && yarn test:php:multisite --group ajax

    - name: PHP 7.2 unit tests
      env: INSTALL_COMPOSER=true LOCAL_PHP=7.2-fpm
      script:
        - yarn test:php && yarn test:php --group ajax

    - name: PHP 7.1 unit tests
      env: INSTALL_COMPOSER=true LOCAL_PHP=7.1-fpm
      script:
        - yarn test:php && yarn test:php --group ajax

    - name: PHP 7.0 unit tests
      env: INSTALL_COMPOSER=true LOCAL_PHP=7.0-fpm
      script:
        - yarn test:php && yarn test:php --group ajax

    - name: PHP 5.6 unit tests
      env: INSTALL_COMPOSER=true LOCAL_PHP=5.6-fpm
      script:
        - yarn test:php && yarn test:php --group ajax

    - name: PHP 7.4 unit tests
      env: INSTALL_COMPOSER=true LOCAL_PHP=7.4-fpm
      script:
        - yarn test:php && yarn test:php --group ajax
  allow_failures:
    - INSTALL_COMPOSER=true LOCAL_PHP=7.4-fpm